/*import i18next from '@/i18n';
import { IPortfolioCardFull } from '@/components/Portfolio/types';

export const portfolioCardDB: IPortfolioCardFull[] = [
    {
        id: '12',
        title: i18next.t('portfolioCard.title.title12'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2025,
        design: '+',
        role: i18next.t('portfolioCard.role1'),
        tag: ['React.js', 'SCSS', 'JS', 'BEM'],
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type2'),
        url: 'https://andrey2528.github.io/GrillCalc/',
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg12-x4RM-yzB.webp',
        description: i18next.t('portfolioCard.description.description12'),
        timeToEndWork: `3 ${i18next.t('portfolioCard.timeWork.Hours1')}`,
    },
    {
        id: '11',
        title: i18next.t('portfolioCard.title.title11'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2025,
        design: '-',
        role: i18next.t('portfolioCard.role1'),
        tag: ['React.js', 'SCSS', 'JS', 'BEM', 'SEO'],
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type3'),
        url: 'https://andrey2528.github.io/PortfolioAZ/#/',
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg11-yWW74hzU.webp',
        description: i18next.t('portfolioCard.description.description11'),
        timeToEndWork: `20 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '10',
        title: i18next.t('portfolioCard.title.title9'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2024,
        design: '-',
        role: i18next.t('portfolioCard.role1'),
        tag: ['HTML', 'CSS', 'JS', 'jQuery', 'BEM', 'SEO'],
        platform: i18next.t('portfolioCard.platform1'),
        type: i18next.t('portfolioCard.type3'),
        url: i18next.t('portfolioCard.urlNotAviable'),
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg10-CtA7_jIj.webp',
        description: i18next.t('portfolioCard.description.description9'),
        timeToEndWork: `50 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '9',
        title: i18next.t('portfolioCard.title.title10'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2023,
        design: '+',
        role: i18next.t('portfolioCard.role1'),
        tag: ['HTML', 'CSS', 'JS', 'jQuery', 'BEM', 'SEO'],
        platform: i18next.t('portfolioCard.platform1'),
        type: i18next.t('portfolioCard.type3'),
        url: 'https://andrey2528.github.io/1_drop_socks/',
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg9-BwsxAT-b.webp',
        description: i18next.t('portfolioCard.description.description10'),
        timeToEndWork: `7 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '8',
        title: i18next.t('portfolioCard.title.title8'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2023,
        design: '-',
        role: i18next.t('portfolioCard.role1'),
        tag: ['HTML', 'CSS', 'JS', 'jQuery', 'BEM', 'SEO'],
        platform: i18next.t('portfolioCard.platform1'),
        type: i18next.t('portfolioCard.type3'),
        url: 'http://sketch2site.com',
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg8-gMkRFxOS.webp',
        description: i18next.t('portfolioCard.description.description8'),
        timeToEndWork: `30 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '7',
        title: `${i18next.t('portfolioCard.title.title7')} ${i18next.t('portfolioCard.old')}`,
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2023,
        design: '-',
        role: `${i18next.t('portfolioCard.role1')}, ${i18next.t('portfolioCard.role2')}`,
        tag: ['HTML', 'CSS', 'PHP', 'WordPress', 'JS', 'jQuery', 'BEM', 'SEO'],
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type1'),
        url: 'http://batumikarting.ge',
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg7-BgCa2at9.webp',
        description: i18next.t('portfolioCard.description.description7'),
        timeToEndWork: `200 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '6',
        title: i18next.t('portfolioCard.title.title6'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2022,
        design: '-',
        role: `${i18next.t('portfolioCard.role1')}, ${i18next.t('portfolioCard.role3')}, ${i18next.t('portfolioCard.role4')}`,
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type2'),
        tag: ['HTML', 'SCSS', 'JS', 'React.js', 'BEM'],
        url: i18next.t('portfolioCard.urlNotAviable'),
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg6-DKObKo2i.webp',
        description: i18next.t('portfolioCard.description.description6'),
        timeToEndWork: `15 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '5',
        title: i18next.t('portfolioCard.title.title5'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2022,
        design: '-',
        role: `${i18next.t('portfolioCard.role1')}, ${i18next.t('portfolioCard.role3')}, ${i18next.t('portfolioCard.role4')}`,
        tag: ['HTML', 'CSS', 'PHP', 'WordPress', 'JS', 'jQuery', 'BEM', 'SEO'],
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type3'),
        url: i18next.t('portfolioCard.urlNotAviable'),
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg5-C5wJWQCn.webp',
        description: i18next.t('portfolioCard.description.description5'),
        timeToEndWork: `100 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '4',
        title: i18next.t('portfolioCard.title.title4'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2022,
        design: '-',
        role: `${i18next.t('portfolioCard.role1')}, ${i18next.t('portfolioCard.role3')}`,
        tag: ['HTML', 'CSS', 'JS', 'jQuery', 'BEM'],
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type2'),
        url: 'https://andrey2528.github.io/people-taback/',
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg4-OWjBVQTc.webp',
        description: i18next.t('portfolioCard.description.description4'),
        timeToEndWork: `9 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '3',
        title: i18next.t('portfolioCard.title.title3'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2022,
        design: '-',
        role: `${i18next.t('portfolioCard.role1')}, ${i18next.t('portfolioCard.role3')}, ${i18next.t('portfolioCard.role4')}`,
        tag: ['HTML', 'CSS', 'JS', 'jQuery', 'BEM', 'SEO'],
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type3'),
        url: 'https://fairpartner.pl/',
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg3-BY486qLq.webp',
        description: i18next.t('portfolioCard.description.description3'),
        timeToEndWork: `20 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '2',
        title: i18next.t('portfolioCard.title.title2'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2019,
        design: '-',
        role: i18next.t('portfolioCard.role1'),
        tag: ['HTML', 'CSS', 'JS', 'jQuery', 'BEM'],
        platform: i18next.t('portfolioCard.platform2'),
        type: i18next.t('portfolioCard.type2'),
        url: i18next.t('portfolioCard.urlNotAviable'),
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg2-3HifPg_d.webp',
        description: i18next.t('portfolioCard.description.description2'),
        timeToEndWork: `10 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
    {
        id: '1',
        title: i18next.t('portfolioCard.title.title1'),
        subTitle: i18next.t('portfolioCard.subTitle'),
        year: 2019,
        design: '-',
        role: i18next.t('portfolioCard.role1'),
        tag: ['HTML', 'CSS'],
        platform: i18next.t('portfolioCard.platform1'),
        type: i18next.t('portfolioCard.type2'),
        url: i18next.t('portfolioCard.urlNotAviable'),
        img: 'https://andrey2528.github.io/PortfolioAZ_TypeScript/assets/portfolioImg1-BB90i1t3.webp',
        description: i18next.t('portfolioCard.description.description1'),
        timeToEndWork: `10 ${i18next.t('portfolioCard.timeWork.Hours2')}`,
    },
];

export default portfolioCardDB;
*/
